version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    ports:
    - 8099:80
    links:
      - app
    volumes:
      - ./:/var/www
  app:
    build:
      context: .
      dockerfile: docker/fpm.Dockerfile
    environment:
      SERVICE_NAME: app
      SERVICE_TAG: dev
    volumes:
      - ./docker/php-fpm/php7.3.ini:/usr/local/etc/php/php.ini
      - ./:/var/www
    links:
      - mysql
  mysql:
    image: mysql:latest
    ports:
      - 33062:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=phalcon
    volumes:
    - ./docker/mysql/data:/var/lib/mysql
